/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.TrabalhoMerci.apresentacao;

import br.edu.ifnmg.TrabalhoMerci.entidade.GrupoUsuarios;
import br.edu.ifnmg.TrabalhoMerci.entidade.Usuarios;
import br.edu.ifnmg.TrabalhoMerci.excecao.GrupoUsuarioNaoSelecionadoException;
import br.edu.ifnmg.TrabalhoMerci.excecao.NomeNaoPreenchidoException;
import br.edu.ifnmg.TrabalhoMerci.excecao.SenhaNaoPreenchidaException;
import br.edu.ifnmg.TrabalhoMerci.excecao.TratarMerciExceptions;
import br.edu.ifnmg.TrabalhoMerci.excecao.loginNaoPreenchidoException;
import br.edu.ifnmg.TrabalhoMerci.negocio.UsuarioBO;
import br.edu.ifnmg.TrabalhoMerci.negocio.UsuariosGrupoBO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author victor
 */
public class TelaUsuarios extends javax.swing.JFrame {

    //private Usuarios usuarios = new Usuarios();
    private UsuarioBO usuarioBO = new UsuarioBO();
    private UsuariosGrupoBO usuariosGrupoBO = new UsuariosGrupoBO();
            
    public TelaUsuarios() throws SQLException, GrupoUsuarioNaoSelecionadoException {
        initComponents();
        setLocationRelativeTo(null);
        limitaTamanhoString();
        modoNovoUsuario();
        recuperaDadosInseridos();
    }
      
    public void modoNovoUsuario(){
        btnUsuariosNovo.setEnabled(false);
        btnUsuariosExcluir.setEnabled(false);
        btnUsuariosSalvar.setEnabled(true);
    }
    
    public void modoComUsuario(){
            btnUsuariosSalvar.setEnabled(false);
    }
    
    public void limitaTamanhoString(){
        txtUsuariosNome.setDocument(new ControlaEntradaDados(60,"[^a-z A-Z]"));
        txtUsuariosLogin.setDocument(new ControlaEntradaDados(8,"[^a-zA-Z0-9]"));
        txtUsuariosSenha.setDocument(new ControlaEntradaDados(8,"[^a-zA-Z0-9]"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnUsuariosFechar = new javax.swing.JButton();
        txtUsuariosNome = new javax.swing.JTextField();
        btnUsuariosSalvar = new javax.swing.JButton();
        btnUsuariosPesquisar = new javax.swing.JButton();
        btnUsuariosNovo = new javax.swing.JButton();
        txtUsuariosLogin = new javax.swing.JTextField();
        lblUsuariosLogin = new javax.swing.JLabel();
        txtUsuariosSenha = new javax.swing.JPasswordField();
        lblUsuariosNome = new javax.swing.JLabel();
        lblUsuariosSenha = new javax.swing.JLabel();
        btnUsuariosExcluir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        optUsuariosGerente = new javax.swing.JCheckBox();
        optUsuariosGestorEstoque = new javax.swing.JCheckBox();
        optUsuariosGestorCompras = new javax.swing.JCheckBox();
        optUsuariosCaixeiro = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Usuários");
        setName("TelaUsuarios"); // NOI18N

        btnUsuariosFechar.setText("Fechar");
        btnUsuariosFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosFecharActionPerformed(evt);
            }
        });

        btnUsuariosSalvar.setText("Salvar");
        btnUsuariosSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosSalvarActionPerformed(evt);
            }
        });

        btnUsuariosPesquisar.setText("Pesquisar");

        btnUsuariosNovo.setText("Novo");

        lblUsuariosLogin.setText("Login");

        lblUsuariosNome.setText("Nome");

        lblUsuariosSenha.setText("Senha");

        btnUsuariosExcluir.setText("Excluir");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Grupos do Usuário"));

        optUsuariosGerente.setText("Gerente");

        optUsuariosGestorEstoque.setText("Gestor de Estoque");

        optUsuariosGestorCompras.setText("Gestor de Compras");

        optUsuariosCaixeiro.setText("Caixeiro");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optUsuariosGerente)
                    .addComponent(optUsuariosGestorEstoque))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optUsuariosGestorCompras)
                    .addComponent(optUsuariosCaixeiro))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optUsuariosGerente)
                    .addComponent(optUsuariosGestorCompras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optUsuariosGestorEstoque)
                    .addComponent(optUsuariosCaixeiro))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblUsuariosNome)
                .addGap(8, 8, 8)
                .addComponent(txtUsuariosNome, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblUsuariosLogin)
                .addGap(12, 12, 12)
                .addComponent(txtUsuariosLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblUsuariosSenha)
                .addGap(12, 12, 12)
                .addComponent(txtUsuariosSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnUsuariosNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(btnUsuariosPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnUsuariosSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnUsuariosExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUsuariosFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuariosNome, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsuariosNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblUsuariosLogin))
                    .addComponent(txtUsuariosLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuariosSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsuariosSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUsuariosNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUsuariosPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUsuariosSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUsuariosExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUsuariosFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsuariosFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosFecharActionPerformed
        dispose();
    }//GEN-LAST:event_btnUsuariosFecharActionPerformed

    private void btnUsuariosSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosSalvarActionPerformed
        try{
            //if(this.recuperaDadosInseridos() && this.verificaCamposPreenchidos()){
                verificaCamposPreenchidos();
                Usuarios usuarios = extrairDadosUsuario();
                if(usuarioBO.inserirUsuario(usuarios))
                    JOptionPane.showMessageDialog(null,"Usuario cadastrado com sucesso!!!");
                else JOptionPane.showMessageDialog(null, "Erro ao cadastrar Usuario","Merci 1.0",JOptionPane.ERROR_MESSAGE);
            
        }catch(TratarMerciExceptions e){
            JOptionPane.showMessageDialog(null, e.getMessage(),"Merci 1.0",JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(TelaUsuarios.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnUsuariosSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaUsuarios().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(TelaUsuarios.class.getName()).log(Level.SEVERE, null, ex);
                } catch (GrupoUsuarioNaoSelecionadoException ex) {
                    Logger.getLogger(TelaUsuarios.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUsuariosExcluir;
    private javax.swing.JButton btnUsuariosFechar;
    private javax.swing.JButton btnUsuariosNovo;
    private javax.swing.JButton btnUsuariosPesquisar;
    private javax.swing.JButton btnUsuariosSalvar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblUsuariosLogin;
    private javax.swing.JLabel lblUsuariosNome;
    private javax.swing.JLabel lblUsuariosSenha;
    private javax.swing.JCheckBox optUsuariosCaixeiro;
    private javax.swing.JCheckBox optUsuariosGerente;
    private javax.swing.JCheckBox optUsuariosGestorCompras;
    private javax.swing.JCheckBox optUsuariosGestorEstoque;
    private javax.swing.JTextField txtUsuariosLogin;
    private javax.swing.JTextField txtUsuariosNome;
    private javax.swing.JPasswordField txtUsuariosSenha;
    // End of variables declaration//GEN-END:variables
    
    private boolean recuperaDadosInseridos() throws SQLException, GrupoUsuarioNaoSelecionadoException{
    
        GrupoUsuarios grupoUsuarios = new GrupoUsuarios();
        Usuarios usuarios = new Usuarios();
        boolean selecao = false;
        
        try{
        
        if(this.optUsuariosGerente.isSelected()){
            grupoUsuarios.setGerente(1);
            selecao = true;
        }
        if(this.optUsuariosGestorEstoque.isSelected()){
            grupoUsuarios.setGestorEstoque(1);
            selecao = true;
        }
        if(this.optUsuariosGestorCompras.isSelected()){
            grupoUsuarios.setGestorCompras(1);
            selecao = true;
        }
        if(this.optUsuariosCaixeiro.isSelected()){
            grupoUsuarios.setCaixeiro(1);
            selecao = true;
        }
        
        if(selecao!=true)
            throw new GrupoUsuarioNaoSelecionadoException();
        else usuarios.setGrupoUsuarios(grupoUsuarios);  
       
        }catch(TratarMerciExceptions e){
           System.out.println(e.getMessage());
        }
        return selecao;
    }
    
    private void verificaCamposPreenchidos() throws loginNaoPreenchidoException, NomeNaoPreenchidoException, SenhaNaoPreenchidaException{
        String campoLogin = txtUsuariosLogin.getText();
        String campoNome = txtUsuariosNome.getText();
        String campoSenha = txtUsuariosSenha.getText();

        if (campoLogin.trim().isEmpty()) {
            throw new loginNaoPreenchidoException();
        }

        if (campoNome.trim().isEmpty()) {
            throw new NomeNaoPreenchidoException();
        }

        if (campoSenha.isEmpty()) {
            throw new SenhaNaoPreenchidaException();
        }
    }  
    
    private Usuarios extrairDadosUsuario(){
        Usuarios usuarios = new Usuarios();
        usuarios.setLogin(txtUsuariosLogin.getText());
        usuarios.setNome(txtUsuariosNome.getText());
        usuarios.setSenha(txtUsuariosSenha.getText());
        return usuarios;
    }
}
