/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.TrabalhoMerci.apresentacao;

import br.edu.ifnmg.TrabalhoMerci.entidade.GrupoUsuarios;
import br.edu.ifnmg.TrabalhoMerci.entidade.Usuarios;
import br.edu.ifnmg.TrabalhoMerci.excecao.GrupoUsuarioNaoSelecionadoException;
import br.edu.ifnmg.TrabalhoMerci.excecao.NomeNaoPreenchidoException;
import br.edu.ifnmg.TrabalhoMerci.excecao.SenhaNaoPreenchidaException;
import br.edu.ifnmg.TrabalhoMerci.excecao.TratarMerciExceptions;
import br.edu.ifnmg.TrabalhoMerci.excecao.UsuarioNaoEncontradoException;
import br.edu.ifnmg.TrabalhoMerci.excecao.confirmaSenhaInvalidaException;
import br.edu.ifnmg.TrabalhoMerci.excecao.loginNaoPreenchidoException;
import br.edu.ifnmg.TrabalhoMerci.negocio.UsuarioBO;
import br.edu.ifnmg.TrabalhoMerci.negocio.UsuariosGrupoBO;
import br.edu.ifnmg.TrabalhoMerci.persistencia.UsuariosDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author victor
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private TelaUsuarios telaUsuarios;
    private Usuarios usuarios = new Usuarios();
    private UsuariosDAO usuariosDAO;
    private UsuarioBO usuarioBO = new UsuarioBO();
    
    public TelaPrincipal() throws SQLException, GrupoUsuarioNaoSelecionadoException {
        this.telaUsuarios = new TelaUsuarios();
        initComponents();
        setLocationRelativeTo(null);
        modoSemUsuario();
        defineTamanhoString();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvas1 = new java.awt.Canvas();
        jPanel1 = new javax.swing.JPanel();
        btnConfirmarSenha = new javax.swing.JButton();
        txtPrincipalConfirmarSenha = new javax.swing.JPasswordField();
        txtPrincipalLogin = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        lblConfirmarSenha = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        txtPrincipalSenha = new javax.swing.JPasswordField();
        btnAlterarSenha = new javax.swing.JButton();
        btnLogoff = new javax.swing.JButton();
        MenuMerci = new javax.swing.JMenuBar();
        itemGestao = new javax.swing.JMenu();
        itemGestaoUsuarios = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        itemGestaoFornecedores = new javax.swing.JMenuItem();
        itemGestaoMercadorias = new javax.swing.JMenuItem();
        itemGestaoPedidosCompra = new javax.swing.JMenuItem();
        itemGestaoEstoque = new javax.swing.JMenuItem();
        itemGestaoAbrirCaixa = new javax.swing.JMenuItem();
        itemGestaoSair = new javax.swing.JMenuItem();
        itemVendas = new javax.swing.JMenu();
        itemAjuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Merci 1.0 - Tela Principal");
        setName("TelaPrincipal"); // NOI18N

        btnConfirmarSenha.setText("Confirmar Senha");
        btnConfirmarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarSenhaActionPerformed(evt);
            }
        });

        txtPrincipalLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrincipalLoginActionPerformed(evt);
            }
        });

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblConfirmarSenha.setText("Confirmar Senha");

        lblLogin.setText("Login");

        lblSenha.setText("Senha");

        txtPrincipalSenha.setToolTipText("");

        btnAlterarSenha.setText("Alterar Senha");

        btnLogoff.setText("Logoff");
        btnLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSenha)
                            .addComponent(lblConfirmarSenha)
                            .addComponent(lblLogin))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrincipalSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrincipalLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrincipalConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnLogoff)
                        .addGap(18, 18, 18)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAlterarSenha)
                        .addGap(18, 18, 18)
                        .addComponent(btnConfirmarSenha)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLogoff, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAlterarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrincipalLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLogin))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSenha)
                            .addComponent(txtPrincipalSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblConfirmarSenha)
                            .addComponent(txtPrincipalConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 92, Short.MAX_VALUE)))
                .addGap(31, 31, 31))
        );

        MenuMerci.setBackground(new java.awt.Color(242, 241, 240));
        MenuMerci.setForeground(new java.awt.Color(1, 1, 1));

        itemGestao.setForeground(new java.awt.Color(1, 1, 1));
        itemGestao.setText("Gestão");
        itemGestao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGestaoActionPerformed(evt);
            }
        });

        itemGestaoUsuarios.setText("Usuários");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setText("Cadastrar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        itemGestaoUsuarios.add(jMenuItem2);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Listar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        itemGestaoUsuarios.add(jMenuItem1);

        itemGestao.add(itemGestaoUsuarios);

        itemGestaoFornecedores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        itemGestaoFornecedores.setText("Fornecedores");
        itemGestao.add(itemGestaoFornecedores);

        itemGestaoMercadorias.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        itemGestaoMercadorias.setText("Mercadorias");
        itemGestao.add(itemGestaoMercadorias);

        itemGestaoPedidosCompra.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        itemGestaoPedidosCompra.setText("Pedidos de Compra");
        itemGestao.add(itemGestaoPedidosCompra);

        itemGestaoEstoque.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        itemGestaoEstoque.setText("Estoque");
        itemGestao.add(itemGestaoEstoque);

        itemGestaoAbrirCaixa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        itemGestaoAbrirCaixa.setText("Abrir Caixa");
        itemGestao.add(itemGestaoAbrirCaixa);

        itemGestaoSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        itemGestaoSair.setText("Sair");
        itemGestaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGestaoSairActionPerformed(evt);
            }
        });
        itemGestao.add(itemGestaoSair);

        MenuMerci.add(itemGestao);

        itemVendas.setForeground(new java.awt.Color(147, 140, 140));
        itemVendas.setText("Vendas");
        itemVendas.setEnabled(false);
        MenuMerci.add(itemVendas);

        itemAjuda.setForeground(new java.awt.Color(1, 1, 1));
        itemAjuda.setText("Ajuda");
        itemAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAjudaActionPerformed(evt);
            }
        });
        MenuMerci.add(itemAjuda);

        setJMenuBar(MenuMerci);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemGestaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGestaoSairActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Deseja realmente sair do sistema?")==0)
            System.exit(0);
        //System.exit(0);
    }//GEN-LAST:event_itemGestaoSairActionPerformed

    private void itemGestaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGestaoActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_itemGestaoActionPerformed

    private void itemAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAjudaActionPerformed
        JOptionPane.showMessageDialog(null,"Não fornecemos ajuda online","Mensagem de alerta",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_itemAjudaActionPerformed

    private void btnConfirmarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmarSenhaActionPerformed

    private void txtPrincipalLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrincipalLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrincipalLoginActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
          try {
                    verificaCamposPreenchidos();
                    this.autenticar();
                    modoComUsuario();
                    limpaCamposUsuario();
               
               
               
            JOptionPane.showMessageDialog(null,"Login realizado com sucesso","Mensagem de Confirmação",JOptionPane.INFORMATION_MESSAGE);
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage(),"Mensagem de Erro",JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoffActionPerformed
        modoSemUsuario();
        limpaCamposUsuario();
    }//GEN-LAST:event_btnLogoffActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JOptionPane.showMessageDialog(null,"Função ainda em implementação","Mensagem de aviso",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try {
            new TelaUsuarios().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (GrupoUsuarioNaoSelecionadoException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */

    /**
     *
     * @param args
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaPrincipal().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                } catch (GrupoUsuarioNaoSelecionadoException ex) {
                    Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuMerci;
    private javax.swing.JButton btnAlterarSenha;
    private javax.swing.JButton btnConfirmarSenha;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogoff;
    private java.awt.Canvas canvas1;
    private javax.swing.JMenu itemAjuda;
    private javax.swing.JMenu itemGestao;
    private javax.swing.JMenuItem itemGestaoAbrirCaixa;
    private javax.swing.JMenuItem itemGestaoEstoque;
    private javax.swing.JMenuItem itemGestaoFornecedores;
    private javax.swing.JMenuItem itemGestaoMercadorias;
    private javax.swing.JMenuItem itemGestaoPedidosCompra;
    private javax.swing.JMenuItem itemGestaoSair;
    private javax.swing.JMenu itemGestaoUsuarios;
    private javax.swing.JMenu itemVendas;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblConfirmarSenha;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JPasswordField txtPrincipalConfirmarSenha;
    private javax.swing.JTextField txtPrincipalLogin;
    private javax.swing.JPasswordField txtPrincipalSenha;
    // End of variables declaration//GEN-END:variables
    
    public void modoSemUsuario(){
        btnLogin.setEnabled(true);
        btnLogoff.setEnabled(false);
        btnAlterarSenha.setEnabled(false);
        btnConfirmarSenha.setEnabled(false);
        lblConfirmarSenha.setEnabled(false);
        txtPrincipalConfirmarSenha.setEnabled(false);
        itemGestaoUsuarios.setEnabled(false);
        itemGestaoEstoque.setEnabled(false);
        itemGestaoAbrirCaixa.setEnabled(false);
        itemGestaoFornecedores.setEnabled(false);
        itemGestaoMercadorias.setEnabled(false);
        itemGestaoPedidosCompra.setEnabled(false);
        //this.itemGestao.setEnabled(false);
    }
    
    public void modoComUsuario(){
        btnLogin.setEnabled(false);
        btnLogoff.setEnabled(true);
        btnAlterarSenha.setEnabled(true);
        itemGestaoEstoque.setEnabled(true);
        itemGestaoAbrirCaixa.setEnabled(true);
        itemGestaoFornecedores.setEnabled(true);
        itemGestaoMercadorias.setEnabled(true);
        itemGestaoPedidosCompra.setEnabled(true);
        itemGestaoUsuarios.setEnabled(true);
    }
        
    public void defineTamanhoString(){
        txtPrincipalLogin.setDocument(new ControlaEntradaDados(8,"[^a-zA-Z0-9]"));
        txtPrincipalSenha.setDocument(new ControlaEntradaDados(8,"[^a-zA-Z0-9]"));
        txtPrincipalConfirmarSenha.setDocument(new ControlaEntradaDados(8,"[^a-zA-Z0-9]"));
    }
    
    public void limpaCamposUsuario(){
        txtPrincipalLogin.setText("");
        txtPrincipalSenha.setText("");
    }
    private void autenticar() throws SQLException, UsuarioNaoEncontradoException{
       UsuarioBO usuarioBO = new UsuarioBO();
       usuarios.setLogin(txtPrincipalLogin.getText());
       usuarios.setSenha(txtPrincipalSenha.getText());
       usuarioBO.autenticar(txtPrincipalLogin.getText(),txtPrincipalSenha.getText());
    }
         
    private void recuperarDadosInseridos() throws loginNaoPreenchidoException, confirmaSenhaInvalidaException{
         String login = txtPrincipalLogin.getText().trim();
         String senha = new String (txtPrincipalSenha.getPassword()).trim();
         String confirmaSenha = new String(txtPrincipalConfirmarSenha.getPassword()).trim();
         if(!login.isEmpty())
                usuarios.setLogin(login);
         else
            throw new loginNaoPreenchidoException();
        
        if(!senha.isEmpty())
            usuarios.setSenha(senha);
        
        if(!confirmaSenha.isEmpty())
            if(!confirmaSenha.equals(senha))
                throw new confirmaSenhaInvalidaException();
    }
     
    private void verificaCamposPreenchidos() throws loginNaoPreenchidoException, SenhaNaoPreenchidaException{
        String campoLogin = this.txtPrincipalLogin.getText();
        String campoSenha = this.txtPrincipalSenha.getText();
        boolean campoPreenchido = false;
       
            if(campoLogin.trim().isEmpty()){
                campoPreenchido = true;
                throw new loginNaoPreenchidoException(); 
            }else if(campoSenha.isEmpty()){
                        campoPreenchido = true;
                        throw new SenhaNaoPreenchidaException();
                  }
        
    }
     
    private void cadastrar() throws SQLException{
        UsuarioBO usuarioBO = new UsuarioBO();
    } 
}



